accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup")
]

blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView,BlogDeleteView

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/",BlogDeleteView.as_view(),name="post_delete")
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blogs.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

blogs/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post


class BlogListView(ListView):
    model = Post
    template_name = "blogs/home.html"


class BlogDetailView(DetailView):
    model = Post
    template_name = "blogs/post_detail.html"
    context_object_name = "post"


class BlogCreateView(CreateView):
    model = Post
    template_name = "blogs/post_new.html"
    fields = ["title", "author", "body"]



class BlogUpdateView(UpdateView):
    model = Post
    template_name = "blogs/post_edit.html"
    fields = ["title", "body"]


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blogs/post_delete.html"
    success_url = reverse_lazy("home")

accounts/templates/accounts/signup.html
{% extends "_base.html" %}

{% block content %}
    <h2>Sign Up</h2>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}

blogs/templates/blogs/detail.html
{% extends "_base.html" %}

{% block content %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>
{% endblock %}

blogs/templates/blogs/home.html
{% extends "_base.html" %}
{% block content %}
    {% for post in post_list %}
        <div class="post-entry">
            <h2><a href="{% url "post_detail" post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.body }}</p>
        </div>
    {% endfor %}
{% endblock content %}

blogs/templates/blogs/post_delete.html
{% extends "_base.html" %}

{% block content %}
    <h1>Delete Post</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends "_base.html" %}

{% block content %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>

    <p><a href="{% url "post_edit" post.pk %}">+ Edit Blog Post</a></p>
    <p><a href="{% url "post_delete" post.pk %}">+ Delete Blog</a></p>
{% endblock %}

blogs/templates/blogs/post_edit.html
{% extends "_base.html" %}

{% block content %}
    <h1>Edit Post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

blogs/templates/blogs/post_new.html
{% extends "_base.html" %}


{% block content %}
    <h1>New Post</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

templates/_base.html
{% load static %}
<html>
<head>
    <title>Django Blog</title>
    <link rel="stylesheet" href="{% static "_base.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
          rel="stylesheet">
</head>
<body>
<div>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'home' %}">Django blog</a></h1>
        </div>
        <div class="nav-right"><a href="{% url "post_new" %}">+ New Blog Post</a>
        </div>
    </header>
    {% if user.is_authenticated %}
        <p>Hi {{ user.username }}!</p>
        <p><a href="{% url "logout" %}">Log Out</a></p>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url "login" %}">Log In</a> |
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>